namespace FaceSplitScripter
{
    public enum Aspect
    {
        None,
        Air,
        Arcane,
        Artisan,
        Blood,
        Command,
        Death,
        Discipline,
        Earth,
        Eldritch,
        Fire,
        Frost,
        Fortune,
        Gadget,
        Harvest,
        Holy,
        Lightning,
        Lyric,
        Madness,
        Poison,
        Shadow,
        Void,
        War,
        Water
    }

    public enum SkillScroll
    {
        None,
        Alchemy,
        AnimalLore,
        AnimalTame,
        ArmsLore,
        Begging,
        Blacksmithing,
        Camping,
        Carpentry,
        Cartography,
        Chivalry,
        Cooking,
        DetectHidden,
        Discordance,
        Fishing,
        ForensicEvaluation,
        Herding,
        Inscription,
        ItemID,
        Lockpicking,
        LumberJacking,
        Mining,
        Musicianship,
        Necromancy,
        Peacemaking,
        Poisoning,
        Provocation,
        RemoveTrap,
        SpiritSpeak,
        Stealthing,
        Tailoring,
        TasteID,
        Tinkering,
        Tracking,
        Veterinary
    }

    public enum TreasureMapLevel
    {
        None,
        Level1,
        Level2,
        Level3,
        Level4,
        Level5,
        Level6
    }

    public enum LootType
    {
        Core,
        Distill,
        SkillScroll,
        TreasureMap,
        MCD,
        SkillOrb,
        ChromaticCore,
        ChromaticDistill,
        ResourceMapFishing,
        ResourceMapMining,
        ResourceMapLumber,
        ResourceMapSkinning,
        Manual
    }

    public enum ResourceType
    {
        Normal,
        Dull,
        Shadow,
        Copper,
        Bronze,
        Gold,
        Rose,
        Ver,
        Val,
        Ava
    }
}
